# Generated by Django 5.2.17 on 2026-09-15 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name_cn', models.CharField(max_length=32)),
                ('name_latin', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Stratum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('area_ha', models.FloatField(help_text='层总面积 (ha)，由抽样设计给定')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_id', models.CharField(max_length=16, unique=True)),
                ('year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AllometricEquation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equation_id', models.CharField(max_length=32, unique=True)),
                ('response', models.CharField(choices=[('biomass_kg', '地上生物量 (kg)'), ('volume_m3', '蓄积 (m³)')], max_length=16)),
                ('form', models.CharField(choices=[('power_dbh', 'y = a·D^b'), ('power_dbh_height', 'y = a·D^b·H^c')], max_length=32)),
                ('params', models.JSONField(help_text='方程参数，如 {"a":…, "b":…}')),
                ('dbh_unit', models.CharField(default='cm', help_text='方程要求的胸径单位', max_length=8)),
                ('height_unit', models.CharField(default='m', help_text='方程要求的树高单位', max_length=8)),
                ('source', models.CharField(help_text='方程来源/文献', max_length=200)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('confirmed', '已确认')], default='draft', max_length=16)),
                ('supersedes', models.ForeignKey(blank=True, help_text='本方程替代的上一版（旧版保留，不可改）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='forest.allometricequation')),
                ('species', models.ManyToManyField(help_text='适用树种（显式）', related_name='equations', to='forest.species')),
            ],
        ),
        migrations.CreateModel(
            name='EquationSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('set_id', models.CharField(max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('frozen_hash', models.CharField(blank=True, help_text='确认时的内容哈希', max_length=64)),
                ('equations', models.ManyToManyField(related_name='equation_sets', to='forest.allometricequation')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_id', models.CharField(max_length=16, unique=True)),
                ('boundary', models.JSONField(help_text='样地边界 GeoJSON Polygon，EPSG:32650 坐标（开发后端）')),
                ('area_ha', models.FloatField(help_text='样地面积 (ha)，样地间可不等，估计时逐块换算')),
                ('inclusion_probability', models.FloatField(help_text='入样概率 π，由抽样设计给定')),
                ('stratum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plots', to='forest.stratum')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=64)),
                ('dbh_threshold_cm', models.FloatField(default=5.0, help_text='起测胸径 (cm)')),
                ('position_tolerance_m', models.FloatField(default=1.0, help_text='复测位置容差 (m)')),
                ('equation_set_hash', models.CharField(blank=True, help_text='确认时方程集内容哈希快照', max_length=64)),
                ('equation_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forest.equationset')),
                ('survey_t1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forest.survey')),
                ('survey_t2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forest.survey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VerificationTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('conflict', '编号相同但位置矛盾'), ('possible_missed', '疑似初测漏测'), ('dead_without_t1', '死亡记录无初测对应')], max_length=24)),
                ('tree_no_t1', models.CharField(blank=True, max_length=16, null=True)),
                ('tree_no_t2', models.CharField(blank=True, max_length=16, null=True)),
                ('detail', models.TextField()),
                ('status', models.CharField(choices=[('open', '待核实'), ('resolved', '已核实')], default='open', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='forest.plot')),
            ],
        ),
        migrations.CreateModel(
            name='TreeObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_no', models.CharField(help_text='样地内树木编号', max_length=16)),
                ('dbh_value', models.FloatField(blank=True, null=True)),
                ('dbh_unit', models.CharField(blank=True, help_text='显式记录：cm 或 mm', max_length=8)),
                ('height_value', models.FloatField(blank=True, null=True)),
                ('height_unit', models.CharField(blank=True, help_text='显式记录：m 或 cm', max_length=8)),
                ('x_m', models.FloatField(help_text='样地内相对坐标 x (m)')),
                ('y_m', models.FloatField(help_text='样地内相对坐标 y (m)')),
                ('vital_status', models.CharField(choices=[('alive', '存活'), ('dead', '死亡')], default='alive', max_length=8)),
                ('qc_status', models.CharField(choices=[('accepted', '通过'), ('rejected', '拒收')], default='accepted', max_length=8)),
                ('qc_note', models.TextField(blank=True, help_text='单位校验/质检说明')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='forest.plot')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forest.species')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='forest.survey')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('survey', 'plot', 'tree_no'), name='uniq_observation_per_survey')],
            },
        ),
    ]
