# Generated by Django 5.2.17 on 2026-09-15 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyversion',
            name='base_version',
            field=models.ForeignKey(blank=True, help_text='修订来源版（基线）；空表示原始调查版', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='forest.surveyversion'),
        ),
        migrations.AddField(
            model_name='verificationticket',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='RevisionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(help_text='客户端请求标识（幂等键）：重复提交返回同一批次', max_length=64, unique=True)),
                ('payload_fingerprint', models.CharField(help_text='请求内容指纹：同一 request_id 提交不同内容时拒绝', max_length=64)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('applying', '应用中'), ('applied', '已应用'), ('failed', '失败可重试')], default='draft', max_length=16)),
                ('created_by', models.CharField(help_text='批次创建人', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, help_text='应用失败原因（供修正后重试）')),
                ('result_estimates', models.JSONField(blank=True, help_text='应用时的估计结果快照（审计用，原估计永不覆盖）', null=True)),
                ('base_version', models.ForeignKey(help_text='基线调查版（必须为已确认版）', on_delete=django.db.models.deletion.PROTECT, related_name='revision_batches', to='forest.surveyversion')),
                ('result_version', models.OneToOneField(blank=True, help_text='应用成功生成的可追溯新草稿版', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='produced_by_batch', to='forest.surveyversion')),
            ],
        ),
        migrations.AddField(
            model_name='verificationticket',
            name='resolved_by_batch',
            field=models.ForeignKey(blank=True, help_text='核实本工单的修订批次', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tickets', to='forest.revisionbatch'),
        ),
        migrations.CreateModel(
            name='RevisionConclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conclusion_type', models.CharField(choices=[('confirm_renumbered', '同株改号'), ('confirm_missing', '确认漏测'), ('confirm_dead', '确认死亡'), ('keep_excluded', '保留排除'), ('correct_observation', '更正观测记录')], max_length=24)),
                ('operator', models.CharField(help_text='结论操作者', max_length=64)),
                ('request_id', models.CharField(help_text='本条结论的请求标识', max_length=64)),
                ('before_value', models.JSONField(default=dict, help_text='结论前状态快照')),
                ('after_value', models.JSONField(default=dict, help_text='结论内容/更正后值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conclusions', to='forest.revisionbatch')),
                ('source_version', models.ForeignKey(help_text='结论依据的来源调查版', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='forest.surveyversion')),
                ('ticket', models.ForeignKey(blank=True, help_text='关联工单（更正记录类可无工单）', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='conclusions', to='forest.verificationticket')),
            ],
        ),
    ]
